version: "3.5"

services:

  inferno:
    image: 9mine/inferno-os:focal
    container_name: mt-local
    networks:
      - minetest
    ports:
      - "1917:1917"
    volumes:
        - "./profile:/usr/inferno-os/lib/sh/profile"
    stdin_open: true 
    tty: true

  server:
    depends_on: 
      - inferno
    image: 9mine/minetest:master
    container_name: mt-server
    networks:
      - minetest
    volumes:
        - "./storage:/storage"
    ports:
      - "30000:30000/udp"
    environment:
      - INFERNO_ADDR=${INFERNO_ADDR}
      - REFRESH_TIME=${REFRESH_TIME}
networks:
  minetest:
    name: minetest
    driver: bridge
