version: "3.5"

services:
  minetest:
    image: dievri/minetest:${GITHUB_BRANCH}
    networks:
      - minetest-network
    ports:
      - "${MINETEST_PORT}:${MINETEST_PORT}/udp"
    command: --port ${MINETEST_PORT}
  inferno:
    image: dievri/inferno-os:traceroute
    networks:
      - minetest-network
    ports:
      - "${INFERNO_PORT}:${INFERNO_PORT}"
    stdin_open: true
    tty: true

networks:
  minetest-network:
    name: minetest_${GITHUB_BRANCH}
    driver: bridge
