version: "3.5"

services:
  minetest-server:
    build:
      context: .
    volumes:
      - ./mods:/root/.minetest/mods/
    
    networks:
      - minetest
    image: minetest:9pzone
    ports:
      - "30000:30000/udp"
      - "30000:30000"


networks:
  minetest:
    name: minetest
    driver: bridge
