version: "3.5"

services:

  inferno:
    image: dievri/inferno-os:getauth
    container_name: local
    networks:
      - minetest
    ports:
      - "1917:1917"
    stdin_open: true 
    tty: true

  client:
    depends_on: 
      - inferno
    image: dievri/minetest:client
    container_name: mt-client
    environment: 
      - DISPLAY=unix$DISPLAY
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - minetest

  server:
    depends_on: 
      - inferno
      - client
    image: dievri/minetest:auth
    container_name: mt-server
    networks:
      - minetest
    ports:
      - "30000:30000/udp"


networks:
  minetest:
    name: minetest
    driver: bridge