version: "3.5"

services:
  minetest-server:
    build:
      context: .
    volumes:
      - ./graphviz:/root/.minetest/mods/graphviz
    
    networks:
      - minetest
    image: 9mine/minetest:bitcoin_transaction
    ports:
      - "30000:30000/udp"
      - "30000:30000"


  minetest-client:
    build:
      context: .
      dockerfile: Dockerfile.minetest-client
    
    image: minetest-client:bitcoin_transaction
    ports:
      - "5900:5900"
    devices:
      - /dev/dri:/dev/dri #optional
    networks: 
      - minetest

networks:
  minetest:
    name: minetest
    driver: bridge
