version: "3.5"

services:
  minetest:
    image: dievri/minetest:packets
    networks:
      - minetest-packets
    ports:
      - "30000:30000/udp"
  inferno:
    image: dievri/inferno-os
    networks:
      - minetest-packets
    volumes: 
      - ./traceroute.txt:/usr/inferno/traceroute.txt
    command: sh -c 'ndb/cs; ndb/dns; listen -A tcp!*!31000 { export / & };  /dis/sh.dis'
    ports:
      - "31000:31000"

networks:
  minetest-inferno:
    name: minetest_packets
    driver: bridge