version: "3.5"

services:
  minetest:
    image: dievri/minetest:jsonfs
    networks:
      - minetest-jsonfs
    ports:
      - "30000:30000/udp"
  inferno:
    image: dievri/inferno-os
    networks:
      - minetest-jsonfs
    command: sh -c 'ndb/cs; ndb/dns; listen -A tcp!*!31000 { export / & };  /dis/sh.dis'
    ports:
      - "31000:31000"

networks:
  minetest-jsonfs:
    name: minetest_jsonfs
    driver: bridge