version: "3.5"

services:
  minetest-server:
    build:
      context: .
    volumes:
      - ./9pzone:/root/.minetest/mods/9pzone
      - ./mods/default:/root/.minetest/mods/default
      - ./mods/aliveai:/root/.minetest/mods/aliveai
      #- ./mods/npcf:/root/.minetest/mods/npcf
      - ./mods/player_api:/root/.minetest/mods/player_api
    
    networks:
      - minetest
    image: minetest:9pzone
    ports:
      - "30000:30000/udp"
      - "30000:30000"


networks:
  minetest:
    name: minetest
    driver: bridge
