name: Minetest Container Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.10
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: build image
        run: docker build -t ${{ secrets.REGISTRY_ORGANIZATION }}/minetest:${GITHUB_REF##*/} .

      - name: login to hub.docker.com
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: push image to registry
        run: docker image push ${{ secrets.REGISTRY_ORGANIZATION }}/minetest:${GITHUB_REF##*/}

      # - name: build client image
      #   run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/minetest-client:${GITHUB_REF##*/} -f Dockerfile.client .

      # - name: push image to registry
      #   run: docker image push ${{ secrets.REGISTRY_USERNAME }}/minetest-client:${GITHUB_REF##*/}

      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TGBOT_CHAT }}
          token: ${{ secrets.TGBOT_TOKEN }}
          status: ${{ job.status }}
